app.env: dev

db.host:
db.name:
db.username:
db.password:
db.port:
db.encoding: utf8

mail.host:
mail.username:
mail.password:
mail.secure:
mail.port:

media.path:
media.gpx.path:
media.map.path:

site.name:
site.url: